name: automerge

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
  check_suite:
    types: [ completed ]

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: automerge
        uses: fastify/github-action-merge-dependabot@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          merge-method: squash
